services:
  app:
    image: rafadanam/cf23-api:${IMAGE_TAG}
    container_name: cf23-api
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '5600:${APP_PORT}'
    volumes:
      - db_data:/usr/app/db_data
      - live_data:/usr/app/live_data
volumes:
  db_data:
  live_data:
